# Generated by Django 5.0.6 on 2024-09-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_costumer_email_remove_costumer_name_and_more"),
        (
            "order_app",
            "0003_alter_discount_code_alter_discount_initiated_date_and_more",
        ),
        ("product_app", "0004_alter_rate_product_alter_rate_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.costumer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Code should not be more than 10 characters",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Discount Code",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="percentage",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Discount Percentage"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.costumer",
                verbose_name="Customerr",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Order Code",
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "num",
                    models.IntegerField(blank=True, null=True, verbose_name="Quantity"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="This item is related to which order",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_app.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="This product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_app.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.seller",
                        verbose_name="seller",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Order_item",
        ),
    ]
