# Generated by Django 5.0.6 on 2024-09-08 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costumer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="costumer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="costumer",
            name="password",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="email",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="name",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="password",
        ),
        migrations.AlterField(
            model_name="costumer",
            name="username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
